#!/usr/bin/env bash

SRC_DIR="./thermologger"
CONF_DIR="${SRC_DIR}/scripts"

function update_thermo {
  rm -fr /usr/local/src/thermologger.bak
  mv /usr/local/src/thermologger /usr/local/src/thermologger.bak 2> /dev/null
  cp -r ${SRC_DIR} /usr/local/src/

  cp ${CONF_DIR}/usr/local/bin/thermologger /usr/local/bin
  chmod 755 /usr/local/bin/thermologger
}

function update_config {
  mkdir /etc/thermologger 2> /dev/null
  cp ${CONF_DIR}/etc/thermologger/*.json /etc/thermologger
}

function update_tunnel {
  systemd stop neptune-tunnel 2> /dev/null
  systemd stop thermologger 2> /dev/null
  cp ${CONF_DIR}/etc/systemd/* /etc/systemd
  cp ${CONF_DIR}/etc/default/* /etc/default

  systemd reload daemon
  systemd start neptune-tunnel
  systemd strt thermologger
}

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

case $1 in
  "app")
    update_thermo
    ;;
  "config")
    update_config
    ;;
  "tunnel")
    update_tunnel
    ;;
  *)
    echo "usage: installer [app|config|tunnel]"
    ;;
esac





