#!/usr/bin/env bash

SRC_DIR="./thermologger"
CONF_DIR="${SRC_DIR}/scripts"

function update_thermo {
  rm -fr /usr/local/src/thermologger.bak
  mv /usr/local/src/thermologger /usr/local/src/thermologger.bak 2> /dev/null
  cp -r ${SRC_DIR} /usr/local/src/

  cp ${CONF_DIR}/usr/local/bin/thermologger /usr/local/bin
  chmod 755 /usr/local/bin/thermologger
}

function update_config {
  mkdir /etc/thermologger 2> /dev/null
  cp "${CONF_DIR}/etc/thermologger/config.json" /etc/thermologger

}

function update_service() {
  local service=$1
  systemctl stop "$service" 2> /dev/null
  cp "${CONF_DIR}/etc/systemd/system/${service}.service" /etc/systemd/system
  cp "${CONF_DIR}/etc/default/$service" /etc/default 2> /dev/null
  systemctl daemon-reload
  systemctl start $service
}



if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

case $1 in
  "app")
    update_thermo
    update_service "thermologger"
    ;;
  "config")
    update_config
    update_service "thermologger"
    ;;
  "tunnel")
    update_service "neptune-tunnel"
    ;;
  *)
    echo "usage: installer [app|config|tunnel]"
    ;;
esac





